---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test

notifications:
  slack:
    secure: DgRveupfUn8uOuYD6uVcFxT7APkfj49KpK/aA7kohENN4Z9Fe3uHAFlOcFPyad1Cx8b5IwkVCs1q5ekvotWKnHYfCDkMXIWVDxAw6mDQT6X98m0HMTqIszlUO9MS/DcCe9i0PMlwSbzkEO3NTjkHEYbtRXo1oojuO15urmexdC6efWLSZtlxSsUe2W4EV7WX0WetfzGhIJ6c8apNtwTYYCkQXDi1ZT5SNbJTAqYy1+XgNilKDHOVFgAehF0R9/2ebJPFdLC3UozNuOL2aD2aD7KSpihEWUIvLZ7EUSzr+P0mATviM/32r8bZ1jT58YdGqY6LqtdRpMRTf2s6INtQmPhJyne/iyHS7viS/kH1Xkx5rVjOds1mlcODtNzvxKmKDevCKun93UQjYSOANjDa9snuxxOz8/hqYIyhARbDeneMd/BkRl8q1LL+ncxiS0U4j7DToJZ2SAgbFNd84HN2FLWlXgTfgJ4XbN/+bneAIhLaaAqU9u4APKBe4SjJm6obSSLDyHthwdLsBLYmGw4Vn5NQ0M5YC5R5uLhmpJgRr5U1Rjw0rHiLPTQsCTIrGvbLYMjm/MU7u/Vhbz/J8Qte6dAU1eDOhV/nFP/d8qZF42q7ww5TVrgjhj7lB1TDAuq8b7WVYHYyrQyV407vqlgi2f+YMR8LnegebmN38d34lTM=
